// Generated by tools/process_clubs.py from "FIFA Clubs/". Do not edit by hand: change the
// script and re-run it. Each team is [code, full name, short name]; games store "F-" + code.
export const FIFA_COUNTRIES = [
 {
  "id": "eng",
  "name": "England",
  "league": "Premier League",
  "flag": true,
  "teams": [
   [
    "ARS",
    "Arsenal",
    "Arsenal"
   ],
   [
    "AVL",
    "Aston Villa",
    "Aston Villa"
   ],
   [
    "BOU",
    "AFC Bournemouth",
    "Bournemouth"
   ],
   [
    "BRE",
    "Brentford",
    "Brentford"
   ],
   [
    "BHA",
    "Brighton & Hove Albion",
    "Brighton"
   ],
   [
    "CHE",
    "Chelsea",
    "Chelsea"
   ],
   [
    "COV",
    "Coventry City",
    "Coventry"
   ],
   [
    "CRY",
    "Crystal Palace",
    "Crystal Palace"
   ],
   [
    "EVE",
    "Everton",
    "Everton"
   ],
   [
    "FUL",
    "Fulham",
    "Fulham"
   ],
   [
    "HUL",
    "Hull City",
    "Hull City"
   ],
   [
    "IPS",
    "Ipswich Town",
    "Ipswich"
   ],
   [
    "LEE",
    "Leeds United",
    "Leeds"
   ],
   [
    "LIV",
    "Liverpool",
    "Liverpool"
   ],
   [
    "MCI",
    "Manchester City",
    "Man City"
   ],
   [
    "MUN",
    "Manchester United",
    "Man United"
   ],
   [
    "NEW",
    "Newcastle United",
    "Newcastle"
   ],
   [
    "NFO",
    "Nottingham Forest",
    "Nott’m Forest"
   ],
   [
    "SUN",
    "Sunderland",
    "Sunderland"
   ],
   [
    "TOT",
    "Tottenham Hotspur",
    "Tottenham"
   ]
  ]
 },
 {
  "id": "esp",
  "name": "Spain",
  "league": "La Liga",
  "flag": true,
  "teams": [
   [
    "ALA",
    "Deportivo Alavés",
    "Alavés"
   ],
   [
    "ATH",
    "Athletic Club",
    "Athletic"
   ],
   [
    "ATM",
    "Atlético de Madrid",
    "Atlético"
   ],
   [
    "BAR",
    "FC Barcelona",
    "Barcelona"
   ],
   [
    "BET",
    "Real Betis",
    "Betis"
   ],
   [
    "CELT",
    "RC Celta de Vigo",
    "Celta"
   ],
   [
    "DEP",
    "Deportivo de La Coruña",
    "Deportivo"
   ],
   [
    "ELC",
    "Elche CF",
    "Elche"
   ],
   [
    "RCDE",
    "RCD Espanyol",
    "Espanyol"
   ],
   [
    "GET",
    "Getafe CF",
    "Getafe"
   ],
   [
    "LEV",
    "Levante UD",
    "Levante"
   ],
   [
    "MAL",
    "Málaga CF",
    "Málaga"
   ],
   [
    "OSA",
    "CA Osasuna",
    "Osasuna"
   ],
   [
    "RAC",
    "Racing de Santander",
    "Racing"
   ],
   [
    "RAY",
    "Rayo Vallecano",
    "Rayo"
   ],
   [
    "RMA",
    "Real Madrid",
    "Real Madrid"
   ],
   [
    "RSO",
    "Real Sociedad",
    "Real Sociedad"
   ],
   [
    "SEV",
    "Sevilla FC",
    "Sevilla"
   ],
   [
    "VAL",
    "Valencia CF",
    "Valencia"
   ],
   [
    "VIL",
    "Villarreal CF",
    "Villarreal"
   ]
  ]
 },
 {
  "id": "ita",
  "name": "Italy",
  "league": "Serie A",
  "flag": true,
  "teams": [
   [
    "ACM",
    "AC Milan",
    "Milan"
   ],
   [
    "ATA",
    "Atalanta",
    "Atalanta"
   ],
   [
    "BOL",
    "Bologna",
    "Bologna"
   ],
   [
    "CAG",
    "Cagliari",
    "Cagliari"
   ],
   [
    "COM",
    "Como 1907",
    "Como"
   ],
   [
    "FIO",
    "Fiorentina",
    "Fiorentina"
   ],
   [
    "FRO",
    "Frosinone",
    "Frosinone"
   ],
   [
    "GEN",
    "Genoa",
    "Genoa"
   ],
   [
    "INT",
    "Inter",
    "Inter"
   ],
   [
    "JUV",
    "Juventus",
    "Juventus"
   ],
   [
    "LAZ",
    "Lazio",
    "Lazio"
   ],
   [
    "LEC",
    "Lecce",
    "Lecce"
   ],
   [
    "MON",
    "Monza",
    "Monza"
   ],
   [
    "NAP",
    "Napoli",
    "Napoli"
   ],
   [
    "PAR",
    "Parma",
    "Parma"
   ],
   [
    "ROM",
    "AS Roma",
    "Roma"
   ],
   [
    "SAS",
    "Sassuolo",
    "Sassuolo"
   ],
   [
    "TOR",
    "Torino",
    "Torino"
   ],
   [
    "UDI",
    "Udinese",
    "Udinese"
   ],
   [
    "VEN",
    "Venezia",
    "Venezia"
   ]
  ]
 },
 {
  "id": "ger",
  "name": "Germany",
  "league": "Bundesliga",
  "flag": true,
  "teams": [
   [
    "FCA",
    "FC Augsburg",
    "Augsburg"
   ],
   [
    "FCB",
    "FC Bayern München",
    "Bayern"
   ],
   [
    "B04",
    "Bayer 04 Leverkusen",
    "Leverkusen"
   ],
   [
    "BMG",
    "Borussia Mönchengladbach",
    "Gladbach"
   ],
   [
    "BVB",
    "Borussia Dortmund",
    "Dortmund"
   ],
   [
    "SGE",
    "Eintracht Frankfurt",
    "Frankfurt"
   ],
   [
    "SCF",
    "SC Freiburg",
    "Freiburg"
   ],
   [
    "HSV",
    "Hamburger SV",
    "Hamburg"
   ],
   [
    "TSG",
    "TSG Hoffenheim",
    "Hoffenheim"
   ],
   [
    "KOE",
    "1. FC Köln",
    "Köln"
   ],
   [
    "RBL",
    "RB Leipzig",
    "Leipzig"
   ],
   [
    "M05",
    "1. FSV Mainz 05",
    "Mainz"
   ],
   [
    "PAD",
    "SC Paderborn 07",
    "Paderborn"
   ],
   [
    "S04",
    "FC Schalke 04",
    "Schalke"
   ],
   [
    "VFB",
    "VfB Stuttgart",
    "Stuttgart"
   ],
   [
    "SVE",
    "SV Elversberg",
    "Elversberg"
   ],
   [
    "FCU",
    "1. FC Union Berlin",
    "Union Berlin"
   ],
   [
    "SVW",
    "SV Werder Bremen",
    "Werder"
   ]
  ]
 },
 {
  "id": "fra",
  "name": "France",
  "league": "Ligue 1",
  "flag": true,
  "teams": [
   [
    "ANG",
    "Angers SCO",
    "Angers"
   ],
   [
    "AUX",
    "AJ Auxerre",
    "Auxerre"
   ],
   [
    "SB29",
    "Stade Brestois 29",
    "Brest"
   ],
   [
    "HAC",
    "Le Havre AC",
    "Le Havre"
   ],
   [
    "LMA",
    "Le Mans FC",
    "Le Mans"
   ],
   [
    "RCL",
    "RC Lens",
    "Lens"
   ],
   [
    "LIL",
    "LOSC Lille",
    "Lille"
   ],
   [
    "FCL",
    "FC Lorient",
    "Lorient"
   ],
   [
    "OL",
    "Olympique Lyonnais",
    "Lyon"
   ],
   [
    "OM",
    "Olympique de Marseille",
    "Marseille"
   ],
   [
    "ASM",
    "AS Monaco",
    "Monaco"
   ],
   [
    "NIC",
    "OGC Nice",
    "Nice"
   ],
   [
    "PFC",
    "Paris FC",
    "Paris FC"
   ],
   [
    "PSG",
    "Paris Saint-Germain",
    "PSG"
   ],
   [
    "SRF",
    "Stade Rennais",
    "Rennes"
   ],
   [
    "RCS",
    "RC Strasbourg",
    "Strasbourg"
   ],
   [
    "TFC",
    "Toulouse FC",
    "Toulouse"
   ],
   [
    "TRO",
    "ESTAC Troyes",
    "Troyes"
   ]
  ]
 },
 {
  "id": "por",
  "name": "Portugal",
  "league": "Liga Portugal",
  "flag": true,
  "teams": [
   [
    "ALV",
    "FC Alverca",
    "Alverca"
   ],
   [
    "ARO",
    "FC Arouca",
    "Arouca"
   ],
   [
    "AVS",
    "AVS Futebol",
    "AVS"
   ],
   [
    "SLB",
    "SL Benfica",
    "Benfica"
   ],
   [
    "SCB",
    "SC Braga",
    "Braga"
   ],
   [
    "CPI",
    "Casa Pia AC",
    "Casa Pia"
   ],
   [
    "EST",
    "GD Estoril Praia",
    "Estoril"
   ],
   [
    "EAM",
    "Estrela da Amadora",
    "Estrela"
   ],
   [
    "FAM",
    "FC Famalicão",
    "Famalicão"
   ],
   [
    "GIL",
    "Gil Vicente FC",
    "Gil Vicente"
   ],
   [
    "MOR",
    "Moreirense FC",
    "Moreirense"
   ],
   [
    "NAC",
    "CD Nacional",
    "Nacional"
   ],
   [
    "FCP",
    "FC Porto",
    "Porto"
   ],
   [
    "RIO",
    "Rio Ave FC",
    "Rio Ave"
   ],
   [
    "SCL",
    "CD Santa Clara",
    "Santa Clara"
   ],
   [
    "SCP",
    "Sporting CP",
    "Sporting"
   ],
   [
    "TON",
    "CD Tondela",
    "Tondela"
   ],
   [
    "VSC",
    "Vitória SC",
    "Vitória"
   ]
  ]
 },
 {
  "id": "usa",
  "name": "United States",
  "league": "MLS",
  "flag": true,
  "teams": [
   [
    "ATL",
    "Atlanta United",
    "Atlanta"
   ],
   [
    "ATX",
    "Austin FC",
    "Austin"
   ],
   [
    "CLT",
    "Charlotte FC",
    "Charlotte"
   ],
   [
    "CHI",
    "Chicago Fire",
    "Chicago"
   ],
   [
    "CIN",
    "FC Cincinnati",
    "Cincinnati"
   ],
   [
    "RAP",
    "Colorado Rapids",
    "Colorado"
   ],
   [
    "CLB",
    "Columbus Crew",
    "Columbus"
   ],
   [
    "DAL",
    "FC Dallas",
    "Dallas"
   ],
   [
    "DCU",
    "D.C. United",
    "D.C. United"
   ],
   [
    "HOU",
    "Houston Dynamo",
    "Houston"
   ],
   [
    "MIA",
    "Inter Miami",
    "Inter Miami"
   ],
   [
    "SKC",
    "Sporting Kansas City",
    "Kansas City"
   ],
   [
    "LAG",
    "LA Galaxy",
    "LA Galaxy"
   ],
   [
    "LAF",
    "LAFC",
    "LAFC"
   ],
   [
    "MNU",
    "Minnesota United",
    "Minnesota"
   ],
   [
    "MTL",
    "CF Montréal",
    "Montréal"
   ],
   [
    "NSH",
    "Nashville SC",
    "Nashville"
   ],
   [
    "NE",
    "New England Revolution",
    "New England"
   ],
   [
    "NYC",
    "New York City FC",
    "NYCFC"
   ],
   [
    "NYRB",
    "New York Red Bulls",
    "Red Bulls"
   ],
   [
    "ORL",
    "Orlando City",
    "Orlando"
   ],
   [
    "PHI",
    "Philadelphia Union",
    "Philadelphia"
   ],
   [
    "PTFC",
    "Portland Timbers",
    "Portland"
   ],
   [
    "RSL",
    "Real Salt Lake",
    "Salt Lake"
   ],
   [
    "SD",
    "San Diego FC",
    "San Diego"
   ],
   [
    "SJ",
    "San Jose Earthquakes",
    "San Jose"
   ],
   [
    "SEA",
    "Seattle Sounders",
    "Seattle"
   ],
   [
    "STL",
    "St. Louis City SC",
    "St. Louis"
   ],
   [
    "TOFC",
    "Toronto FC",
    "Toronto"
   ],
   [
    "VAN",
    "Vancouver Whitecaps",
    "Vancouver"
   ]
  ]
 },
 {
  "id": "int",
  "name": "National Teams",
  "league": "International",
  "flag": false,
  "teams": [
   [
    "ARG",
    "Argentina",
    "Argentina"
   ],
   [
    "AUS",
    "Australia",
    "Australia"
   ],
   [
    "AUT",
    "Austria",
    "Austria"
   ],
   [
    "BEL",
    "Belgium",
    "Belgium"
   ],
   [
    "BIH",
    "Bosnia and Herzegovina",
    "Bosnia"
   ],
   [
    "BRA",
    "Brazil",
    "Brazil"
   ],
   [
    "CAN",
    "Canada",
    "Canada"
   ],
   [
    "CPV",
    "Cape Verde",
    "Cape Verde"
   ],
   [
    "COL",
    "Colombia",
    "Colombia"
   ],
   [
    "CRO",
    "Croatia",
    "Croatia"
   ],
   [
    "CZE",
    "Czechia",
    "Czechia"
   ],
   [
    "DEN",
    "Denmark",
    "Denmark"
   ],
   [
    "COD",
    "DR Congo",
    "DR Congo"
   ],
   [
    "ECU",
    "Ecuador",
    "Ecuador"
   ],
   [
    "ENG",
    "England",
    "England"
   ],
   [
    "FIN",
    "Finland",
    "Finland"
   ],
   [
    "FRA",
    "France",
    "France"
   ],
   [
    "GER",
    "Germany",
    "Germany"
   ],
   [
    "GHA",
    "Ghana",
    "Ghana"
   ],
   [
    "HAI",
    "Haiti",
    "Haiti"
   ],
   [
    "HUN",
    "Hungary",
    "Hungary"
   ],
   [
    "ISL",
    "Iceland",
    "Iceland"
   ],
   [
    "IDN",
    "Indonesia",
    "Indonesia"
   ],
   [
    "ITA",
    "Italy",
    "Italy"
   ],
   [
    "CIV",
    "Ivory Coast",
    "Ivory Coast"
   ],
   [
    "MEX",
    "Mexico",
    "Mexico"
   ],
   [
    "MAR",
    "Morocco",
    "Morocco"
   ],
   [
    "NED",
    "Netherlands",
    "Netherlands"
   ],
   [
    "NZL",
    "New Zealand",
    "New Zealand"
   ],
   [
    "NIR",
    "Northern Ireland",
    "N. Ireland"
   ],
   [
    "NOR",
    "Norway",
    "Norway"
   ],
   [
    "PAN",
    "Panama",
    "Panama"
   ],
   [
    "PRY",
    "Paraguay",
    "Paraguay"
   ],
   [
    "POL",
    "Poland",
    "Poland"
   ],
   [
    "POR",
    "Portugal",
    "Portugal"
   ],
   [
    "QAT",
    "Qatar",
    "Qatar"
   ],
   [
    "IRL",
    "Republic of Ireland",
    "Ireland"
   ],
   [
    "ROU",
    "Romania",
    "Romania"
   ],
   [
    "KSA",
    "Saudi Arabia",
    "Saudi Arabia"
   ],
   [
    "SCO",
    "Scotland",
    "Scotland"
   ],
   [
    "SEN",
    "Senegal",
    "Senegal"
   ],
   [
    "RSA",
    "South Africa",
    "South Africa"
   ],
   [
    "KOR",
    "South Korea",
    "South Korea"
   ],
   [
    "ESP",
    "Spain",
    "Spain"
   ],
   [
    "SWE",
    "Sweden",
    "Sweden"
   ],
   [
    "SUI",
    "Switzerland",
    "Switzerland"
   ],
   [
    "TUN",
    "Tunisia",
    "Tunisia"
   ],
   [
    "TUR",
    "Türkiye",
    "Türkiye"
   ],
   [
    "UKR",
    "Ukraine",
    "Ukraine"
   ],
   [
    "USA",
    "United States",
    "USA"
   ],
   [
    "URU",
    "Uruguay",
    "Uruguay"
   ],
   [
    "UZB",
    "Uzbekistan",
    "Uzbekistan"
   ],
   [
    "WAL",
    "Wales",
    "Wales"
   ]
  ]
 }
];
