// Single source of truth for team data. Everything that renders a team reads from here.
import { FIFA_COUNTRIES } from './clubs.js';

const t = (abbr, city, nickname, color, name = `${city} ${nickname}`) => ({
  abbr,
  city,
  nickname,
  name,
  color,
  logo: `assets/logos/${abbr.toLowerCase()}.webp`,
});

export const TEAMS = [
  t('ATL', 'Atlanta', 'Hawks', '#E03A3E'),
  t('BOS', 'Boston', 'Celtics', '#007A33'),
  t('BKN', 'Brooklyn', 'Nets', '#000000'),
  t('CHA', 'Charlotte', 'Hornets', '#1D1160'),
  t('CHI', 'Chicago', 'Bulls', '#CE1141'),
  t('CLE', 'Cleveland', 'Cavaliers', '#860038'),
  t('DAL', 'Dallas', 'Mavericks', '#00538C'),
  t('DEN', 'Denver', 'Nuggets', '#0E2240'),
  t('DET', 'Detroit', 'Pistons', '#C8102E'),
  t('GSW', 'Golden State', 'Warriors', '#1D428A'),
  t('HOU', 'Houston', 'Rockets', '#CE1141'),
  t('IND', 'Indiana', 'Pacers', '#002D62'),
  t('LAC', 'Los Angeles', 'Clippers', '#C8102E', 'LA Clippers'),
  t('LAL', 'Los Angeles', 'Lakers', '#552583'),
  t('MEM', 'Memphis', 'Grizzlies', '#5D76A9'),
  t('MIA', 'Miami', 'Heat', '#98002E'),
  t('MIL', 'Milwaukee', 'Bucks', '#00471B'),
  t('MIN', 'Minnesota', 'Timberwolves', '#0C2340'),
  t('NOP', 'New Orleans', 'Pelicans', '#0C2340'),
  t('NYK', 'New York', 'Knicks', '#006BB6'),
  t('OKC', 'Oklahoma City', 'Thunder', '#007AC1'),
  t('ORL', 'Orlando', 'Magic', '#0077C0'),
  t('PHI', 'Philadelphia', '76ers', '#006BB6'),
  t('PHX', 'Phoenix', 'Suns', '#1D1160'),
  t('POR', 'Portland', 'Trail Blazers', '#E03A3E'),
  t('SAC', 'Sacramento', 'Kings', '#5A2D81'),
  t('SAS', 'San Antonio', 'Spurs', '#000000'),
  t('TOR', 'Toronto', 'Raptors', '#CE1141'),
  t('UTA', 'Utah', 'Jazz', '#002B5C'),
  t('WAS', 'Washington', 'Wizards', '#002B5C'),
];

// FIFA teams: the clubs and national teams in "FIFA Clubs/" (see js/clubs.js, generated by
// tools/process_clubs.py). Stored as "F-" + code so they never clash with NBA codes
// (Milan / Bucks, Porto / Portland).
const club = (code, name, nickname, country, logo = `assets/clubs/${code.toLowerCase()}.webp`, color = '#3A3A3C') =>
  ({ key: `F-${code}`, abbr: code, city: '', nickname, name, color, logo, country });

/** Pickable FIFA teams, grouped by country (England → Premier League, …, then National Teams). */
export const FIFA_GROUPS = FIFA_COUNTRIES.map((c) => ({
  id: c.id,
  name: c.name,
  league: c.league,
  flag: c.flag ? `assets/flags/${c.id}.webp` : null,
  teams: c.teams.map(([code, name, short]) => club(code, name, short, c.id)),
}));
export const CLUBS = FIFA_GROUPS.flatMap((g) => g.teams);

// Teams from the first FIFA list that aren't in "FIFA Clubs/". Never offered in the picker;
// kept only so games already logged with them still show a name and badge colour.
const RETIRED_CLUBS = [
  ['WHU', 'West Ham United', 'West Ham', '#7A263A'], ['WOL', 'Wolverhampton Wanderers', 'Wolves', '#231F20'],
  ['GIR', 'Girona', 'Girona', '#CD2534'], ['AJA', 'Ajax', 'Ajax', '#C8102E'], ['PSV', 'PSV', 'PSV', '#C8102E'],
  ['FEY', 'Feyenoord', 'Feyenoord', '#C8102E'], ['CEL', 'Celtic', 'Celtic', '#00804B'], ['RAN', 'Rangers', 'Rangers', '#1B458F'],
  ['GAL', 'Galatasaray', 'Galatasaray', '#A90432'], ['FEN', 'Fenerbahçe', 'Fenerbahçe', '#002D72'],
  ['BOC', 'Boca Juniors', 'Boca Juniors', '#103F79'], ['RIV', 'River Plate', 'River Plate', '#C8102E'],
  ['FLA', 'Flamengo', 'Flamengo', '#C3281E'], ['NAS', 'Al Nassr', 'Al Nassr', '#1D3A8A'], ['HIL', 'Al Hilal', 'Al Hilal', '#1C4E9D'],
  ['ITT', 'Al Ittihad', 'Al Ittihad', '#1D1D1B'], ['JPN', 'Japan', 'Japan', '#1B3F8F'],
].map(([code, name, short, color]) => club(code, name, short, null, null, color));
for (const team of TEAMS) team.key = team.abbr;

const BY_KEY = new Map([...TEAMS, ...CLUBS, ...RETIRED_CLUBS].map((team) => [team.key, team]));

/** Looks up an NBA team ("LAL") or a FIFA team ("F-ARS"). */
export function getTeam(key) {
  const k = String(key || '');
  return BY_KEY.get(k.startsWith('F-') ? k : k.toUpperCase()) || null;
}

/** The team list for a game mode ('2k' or 'fifa'). */
export const teamsFor = (sport) => (sport === 'fifa' ? CLUBS : TEAMS);

const normalize = (s) => s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9 ]/g, '');

/** Matches city, nickname, full name, or abbreviation. Abbreviation / prefix matches rank first. */
export function searchTeams(query, list = TEAMS) {
  const q = normalize(query.trim());
  if (!q) return list;
  const scored = [];
  for (const team of list) {
    const abbr = team.abbr.toLowerCase();
    const fields = [team.city, team.nickname, team.name].map(normalize);
    let score = 0;
    if (abbr === q) score = 4;
    else if (fields.some((f) => f.startsWith(q))) score = 3;
    else if (abbr.startsWith(q)) score = 2;
    else if (fields.some((f) => f.split(' ').some((w) => w.startsWith(q)) || f.includes(q))) score = 1;
    if (score) scored.push([score, team]);
  }
  return scored.sort((a, b) => b[0] - a[0]).map(([, team]) => team);
}
